config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :birds do
    resources :bookings, only: [:new, :create, :show]
  end
  resources :bookings, only: [:index, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bird.rb
class Bird < ApplicationRecord

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  belongs_to :user
  has_many :bookings, dependent: :destroy
  validates :name, presence: true, uniqueness: true
  validates :breed, inclusion: { in: ["Albatross", "Chicken", "Emu", "Flamingo", "Owl", "Parrot", "Penguin", "Turkey"] }
  validates :price, presence: true, :numericality => { :greater_than_or_equal_to => 0 }
  has_one_attached :image
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :bird
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :birds
  # has_many :booked_birds, through: :bookings, source: :birds
  has_many :bookings, dependent: :destroy

  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization
  before_action :authenticate_user!

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/birds_controller.rb
class BirdsController < ApplicationController
  before_action :set_bird, only: [:show, :edit, :destoy, :update]

  def index
    @birds = policy_scope(Bird)

      # the `geocoded` scope filters only flats with coordinates (latitude & longitude)
    @markers = @birds.geocoded.map do |bird|
      {
        lat: bird.latitude,
        lng: bird.longitude,
        info_window: render_to_string(partial: "info_window", locals: { bird: bird }),
				image_url: helpers.asset_url("duckling.png")
      }
    end
  end

  def show
  end

  def new
    @bird = Bird.new
    authorize @bird
  end

  def edit
  end

  def create
    @bird = Bird.new(bird_params)
    @bird.user = current_user
    authorize @bird
    if @bird.save
      redirect_to bird_path(@bird), status: :unprocessable_entity
    else
      render :new, notice: "Your bird could not be created."
    end
  end

  def update
    if @bird.update(bird_params)
      redirect_to @bird, status: :unprocessable_entity
    else
      render :edit, notice: "Bird was successfully updated."
    end
  end

  def destroy
    @bird.destroy
    redirect_to birds_url, notice: "Bird was successfully destroyed."
  end

  private

  def set_bird
    @bird = Bird.find(params[:id])
    authorize @bird
  end

  def bird_params
    params.require(:bird).permit(:name, :breed, :price, :location, :image)
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  after_action :verify_policy_scoped, only: [:index, :show, :destoy], unless: :skip_pundit?

  def index
    @user = current_user
    @bookings = policy_scope(Booking)
    @user_bookings = []
    @bookings.each do |booking|
      @user_bookings << booking if booking.user == current_user
    end
    return @user_bookings
  end

  def show
  end

  def new
    @user = current_user
    @bird = Bird.find(params[:bird_id])
    @booking = Booking.new
    authorize @booking
  end

  def create
    @user = current_user
    @bird = Bird.find(params[:bird_id])
    @booking = Booking.new(user: @user, bird: @bird)
    authorize @booking
    @booking.save!
    if @booking.save!
      @bird.update(status: true)
      redirect_to bird_path(@bird)
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    authorize @booking
    @bird = @booking.bird
    @bird.update(status: false)
    @booking.destroy
    redirect_to bookings_url, notice: "Booking was successfully cancelled."
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/birds/_info_window.html.erb
<h2><%= link_to bird.name, bird_path(bird) %></h2>
<p><%= bird.location %></p>

app/views/birds/edit.html.erb
<div class="container bg-image">
	<h1>Edit Your Bird </h1>

	<%= render "shared/form" %>
</div>

app/views/birds/index.html.erb
<h1 class="text-center">All Birds</h1>

<div class="container bg-image">
		<div class = "row">

				<div class="row">
        <% @birds.each do |bird| %>
        <div class="col list-inline">
					<% unless bird.image.key.nil? %>
						<%= cl_image_tag(bird.image.key, width: 250, height: 250, crop: :thumb, gravity: :face) %>
						<% else %>
						<%= cl_image_tag("placeholderduckling_apfxok", width: 250, height: 250, crop: :thumb, gravity: :face) %>
					<% end %>
          <strong><li> <%= bird.name %> </li></strong>
					<li> <strong>Breed: </strong> <%= bird.breed %></li>
					<li> <strong>Price/day: </strong> <%= bird.price %>0 €</li>
					<li> <strong>Location: </strong> <%= bird.location %></li>
          <%= link_to "View", bird_path(bird) %><br>

        </div><br><br>
      <% end %><br><hr>
    </div>
    <div style="margin:10px 10px 20px 10px; text-align:center;" class="d-grid gap-2 d-md-flex d-grid gap-2 col-4 mx-auto text-center">
		<%= link_to "Add A New Bird",  new_bird_path, class: "btn btn-info ml-1 mt-1 btn-sm" %>
    <%= link_to "Check My Bookings",  bookings_path, class: "btn btn-info ml-1 mt-1 btn-sm" %>
    </div>
</div>

app/views/birds/new.html.erb
<div class="container bg-image">
	<h1>Create a new Bird </h1>

	<%= render "shared/form" %>
</div>

app/views/birds/show.html.erb
<div class="collapse" id="navbarToggleExternalContent">
  <div class="bg-dark p-4">
    <h5 class="text-white h4">Bird BnB</h5>
    <span class="text-muted"></span>
  </div>
</div>
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</nav>

<main>
    <div class="bg-image">
    <section class="py-5 text-center container">
        <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="fw-light">Your Bird</h1>
            <p class="lead text-muted">Bird details:</p>

					<% unless @bird.image.key.nil? %>
						<%= cl_image_tag(@bird.image.key, height: 300, width: 400, crop: :fit) %>
						<% else %>
						<%= cl_image_tag("placeholderduckling_apfxok", height: 300, width: 400, crop: :fit) %>
					<% end %>

                <h3><%= @bird.name %></h3>
                <p>Location: <%= @bird.location %></p>
                <p>Type: <%= @bird.breed %></p>
                <p>Price: <%= @bird.price %>0 €</p>

            <% if @bird.user != current_user  %>
               <% if !@bird.status? %>
                 <div class="btn btn-info"> <%= link_to 'Book', new_bird_booking_path(@bird), :class => "btn" %></div>
               <% else %>
                 <div> <%= @bird.name %> is currently booked! </div>
               <% end %>
            <% end %>

            <% if policy(@bird).edit? %>
               <div class="btn btn-info ml-1 mt-1"> <%= link_to 'Update', edit_bird_path(@bird), :class => "btn" %></div>
               <div class="btn btn-info ml-1 mt-1"> <%= link_to 'Delete', bird_path(@bird), :class => "btn", method: :delete, data: { confirm: "Are you sure?" } %></div>
            <% end %>

            <div class="btn btn-secondary ml-1 mt-1"> <%= link_to 'Back', birds_path(@birds), :class => "btn" %></div>



        </div>
        </div>
    </section>
    </div>
</main>

app/views/bookings/index.html.erb
<div class="container bg-image">
  <div class = "row">
    <h3>Your current bookings:</h3>
  </div>
  <br>
  <div class="list-group">
    <% @user_bookings.each do |booking| %>
      <div class="list-group-item">
        <h3><%= booking.bird.name %></h3>
        <p><%= image_tag booking.bird.image, alt: booking.bird.name, width: 150, height: 150, crop: :thumb, gravity: :face %></p>
                        <p>Location: <%= booking.bird.location %></p>
                        <p>Type: <%= booking.bird.breed %></p>
                        <p>Price: <%= booking.bird.price %>0 €</p>
                        <div class="btn btn-info my-2"> <%= link_to 'Cancel', booking_path(booking), :class => "btn", method: :delete, data: { confirm: "Are you sure?" } %></div>
      </div>
  <% end %>
  </div>
</div><br><br>
<div class="d-flex justify-content-center align-items-end">
  <div class="btn btn-secondary my-2"> <%= link_to 'Back', birds_path(@birds), :class => "btn" %></div>
</div>

app/views/bookings/new.html.erb
<main>
    <div class="bg-image">
    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <p>Do you really want to book <%=@bird.name%>?</p>
                <%= simple_form_for [ @bird, @booking ] do |f| %>
                <%= f.hidden_field :booking, :value => @booking %>
				        <%= cl_image_tag(@bird.image.key, height: 300, width: 400, crop: :fit) %>
                <br><br>
                <%= f.submit "Book", class: "d-grid gap-2 d-md-flex justify-content-md-end btn btn-info align-self-center mx-auto " %>
                <% end %>
            </div>
        </div>
    </section>
    </div>
    </main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BirdBnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Barlow:wght@300&family=Noto+Sans&family=Trispace:wght@600&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<header>
<div class="collapse" id="navbarToggleExternalContent">
  <div class="bg-dark p-4">
    <h5 class="text-white h4">Bird BnB</h5>
    <span class="text-muted"></span>
  </div>
</div>
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</nav>
</header>

<body>
    <div class="bg-image">
        <section class="py-5 text-center container">
            <div class="row py-lg-5">
                <div class="col-lg-6 col-md-8 mx-auto">
                    <h1 class="fw-light">What is Bird Bnb?</h1>
                    <p class="lead text-muted">Bird BnB lets you book a swimming bird for your events or really any other occasion that is bird - friendly.</p>
                    <p>
                    <div class="btn btn-info ml-1 mt-1"> <%= link_to 'Show All Birds', birds_path(@birds), :class => "btn" %></div>
                    <div class="btn btn-secondary ml-1 mt-1"> <%= link_to 'Check Your Bookings', birds_path(@birds), :class => "btn" %></div>

                    <%# <a href="#" class="btn btn-info">Check your bookings</a> %>

                    <div class="btn btn-info ml-1 mt-1"> <%= link_to 'Offer A Bird', new_bird_path, :class => "btn" %></div>
                    </p>
                </div>
            </div>
        </section>
    </div>
</body>

app/views/pages/show.html.erb
<div class="collapse" id="navbarToggleExternalContent">
  <div class="bg-dark p-4">
    <h5 class="text-white h4">Bird BnB</h5>
    <span class="text-muted"></span>
  </div>
</div>
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</nav>

<main>
    <div class="bg-image"></div>
    <section class="py-5 text-center container">
        <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="fw-light">Success! You have created a new bird.</h1>
            <p class="lead text-muted">Here are the details of your bird:</p>
            <ul>
                <% @Bird.each do |bird| %>
                <li><%= bird.name %></li>
                <li><%= bird.location %></li>
                <li><%= bird.type %></li>
                <li><%= bird.price %></li>
                <% end %>
            </ul>
            <a href="#" class="btn btn-info my-2">Find a Bird near you</a>
            <a href="#" class="btn btn-secondary my-2">Check your bookings</a>
            <a href="#" class="btn btn-secondary my-2">Create a bird to rent</a>
            </p>
        </div>
        </div>
    </section>
</main>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_form.html.erb
<div class="container">
  <div class="row justify-content-center">

			<%= simple_form_for [@bird] do |f| %>
				<%= f.input :name, placeholder: 'Please type the name of your bird here!!' %>
				<%= f.input :breed, collection: ["Albatross", "Chicken", "Emu", "Flamingo", "Owl", "Parrot", "Penguin", "Turkey"], prompt: "Select type of your bird"  %>
				<%= f.input :price %>
<div>
				<%= f.input :location, placeholder: 'Please enter the address of your bird', style: "width: 100%",
											input_html: { data: { geocoder_target: "location" }, class: "d-none"  },
											wrapper_html: { data: { controller: "geocoder", geocoder_api_key_value: ENV['MAPBOX_API_KEY'] } } %>
</div>
				<%= f.input :image, as: :file %>
				<%= f.submit class: 'btn btn-info' %>

			<% end %>

  </div>
</div>